from django.db import models

class AnalysisRequest(models.Model):
    """
    I use this model to log all incoming raw schema analysis requests.
    It helps me audit parsing and prediction requests later on.
    """
    PAYLOAD_CHOICES = [
        ('JSON', 'JSON'),
        ('XML', 'XML'),
    ]
    payload_type = models.CharField(
        max_length=4,
        choices=PAYLOAD_CHOICES,
        help_text="Format type of the raw data model payload"
    )
    raw_payload = models.TextField(
        help_text="Unparsed text body of the schema model"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when the request was initiated"
    )

    def __str__(self) -> str:
        return f"Request {self.id} ({self.payload_type}) at {self.created_at}"


class SchemaRecommendation(models.Model):
    """
    Here is where I save the output predictions generated by my ML model.
    """
    request = models.ForeignKey(
        AnalysisRequest,
        on_delete=models.CASCADE,
        related_name='recommendations',
        help_text="Direct relation to the corresponding analysis request"
    )
    predicted_paradigm = models.CharField(
        max_length=50,
        help_text="Predicted database architecture model"
    )
    normalization_target = models.CharField(
        max_length=50,
        help_text="Recommended normal form schema alignment"
    )
    indexing_strategy = models.CharField(
        max_length=50,
        help_text="Recommended table optimization index strategy"
    )
    scaling_strategy = models.CharField(
        max_length=50,
        help_text="Recommended database performance growth path"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Immutable timestamp when the classification was logged"
    )

    def __str__(self) -> str:
        return f"Recommendation for Request {self.request.id} ({self.predicted_paradigm})"
