# Generated by Django 5.0.14 on 2026-06-12 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_type', models.CharField(choices=[('JSON', 'JSON'), ('XML', 'XML')], help_text='Format type of the raw data model payload', max_length=4)),
                ('raw_payload', models.TextField(help_text='Unparsed text body of the schema model')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request was initiated')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_paradigm', models.CharField(help_text='Predicted database architecture model', max_length=50)),
                ('normalization_target', models.CharField(help_text='Recommended normal form schema alignment', max_length=50)),
                ('indexing_strategy', models.CharField(help_text='Recommended table optimization index strategy', max_length=50)),
                ('scaling_strategy', models.CharField(help_text='Recommended database performance growth path', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Immutable timestamp when the classification was logged')),
                ('request', models.ForeignKey(help_text='Direct relation to the corresponding analysis request', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='advisor_engine.analysisrequest')),
            ],
        ),
    ]
